# Architecture 62.2%
arch: birealnet34

# ===== Dataset ===== #
data_url: ../data/imagenet
set: ImageNet
num_classes: 1000
mix_up: 0.0
cutmix: 0.0
auto_augment: None
interpolation: bilinear
re_prob: 0.
re_mode: pixel
re_count: 1
mixup_prob: 1.0
switch_prob: 0.5
mixup_mode: batch
image_size: 224
crop_pct: 0.875


# ===== Learning Rate Policy ======== #
optimizer: adam
base_lr: 0.001
warmup_lr: 0.00001
min_lr: 0.000001
lr_scheduler: linear_lr
warmup_length: 0

# ===== Network training config ===== #
amp_level: O1
beta: [ 0.9, 0.999 ]
clip_global_norm_value: 5.
is_dynamic_loss_scale: True
epochs: 300
cooldown_epochs: 10
label_smoothing: 0.0
weight_decay: 0.
momentum: 0.9
batch_size: 128
drop_path_rate: 0.

# ===== EMA ===== #
with_ema: False
ema_decay: 0.9999

# ===== Hardware setup ===== #
num_parallel_workers: 32
device_target: Ascend